version: 1.0
jobs:
  put-bucket-policy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: "Set bucket policy"
          command: "aws s3api put-bucket-policy --bucket millerd.me --policy file://aws/bucket-policy.json"

  deploy-static-content:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - get-tag:
          directory: millerd
      - run:
          name: "Deploy static content to S3 with Hugo"
          command: |
            cd ./millerd
            hugo -D
            hugo -v deploy --maxDeletes -1
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "Test url"
          command: |
            curl https://millerd.me
