name: Build App

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/build_app.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  AWS_S3_BUCKET_NAME: "millerd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby_version: 2.7
        bundler-cache: true
    - name: "Build Site"
      run: |
        cd app/millerd
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    - name: "Deploy to AWS S3"
      run: |
        cd app/millerd
        aws s3 sync ./_site/ s3://${{ env.AWS_S3_BUCKET_NAME }}
      # - name: "Create AWS Cloudfront Invalidation"
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
